name: flutter_libphonenumber_darwin
description: iOS and macOS implementation of the flutter_libphonenumber plugin.
repository: https://github.com/acoutts/flutter_libphonenumber/tree/main/packages/flutter_libphonenumber_darwin
issue_tracker: https://github.com/acoutts/flutter_libphonenumber/issues
version: 2.2.0

environment:
  sdk: ^3.9.2
  flutter: ">=3.41.0"

resolution: workspace

flutter:
  plugin:
    implements: flutter_libphonenumber
    platforms:
      ios:
        pluginClass: FlutterLibphonenumberPlugin
        dartPluginClass: FlutterLibphonenumberDarwin
        sharedDarwinSource: true
      macos:
        pluginClass: FlutterLibphonenumberPlugin
        dartPluginClass: FlutterLibphonenumberDarwin
        sharedDarwinSource: true

dependencies:
  flutter:
    sdk: flutter
  flutter_libphonenumber_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
